FROM {{ cookiecutter.parent_image }}

LABEL maintainer="{{ cookiecutter.maintainer_name }} <{{ cookiecutter.maintainer_email }}>"

# ARG tool_version=1.0
# ENV TOOL_VERSION ${tool_version}

# RUN set -eux ; \
#     apk add --no-cache \
#         bash \
#         git \
#         tzdata ; \
#     bash --version ; \
#     git --version ; \
#     \
#     rm -rf ~/.cache

CMD ["sh"]
