stages:
  - pre-commit
  - parent-images
  - child-images

.build-push:
  image: docker:19
  services:
    - docker:19-dind
  before_script:
    - docker version
    - apk add --no-cache py3-pip
    - pip3 install --disable-pip-version-check -r requirements.txt
  variables:
    DOCKER_USERNAME: flaudisio
    ENABLE_PUSH: "true"
  script:
    - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_ACCESS_TOKEN"
    - ./build.py
  only:
    - master
    - improve-image-builder

.parent-image:
  extends: .build-push
  stage: parent-images

.child-image:
  extends: .build-push
  stage: child-images

pre-commit Test:
  stage: pre-commit
  image: flaudisio/pre-commit:latest
  script:
    - run-ci-tests

include:
  - local: .gitlab/ci/parent-images.gitlab-ci.yml
  - local: .gitlab/ci/child-images.gitlab-ci.yml
