dist: bionic

language: python

python:
  - 3.6

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=flaudisio
    - PYTHONUNBUFFERED=1

stages:
  - pre-commit
  - base-images
  - child-images

_build_template: &_build_template
  before_install:
    - docker version
  install:
    - pip install -r requirements.txt
  script:
    - |
        if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] ; then
          echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
          export ENABLE_PUSH=1
        fi
    - ./build.py

jobs:
  include:
    - stage: pre-commit
      name: pre-commit Tests
      install:
        - pip install -U pre-commit
      before_script:
        - pre-commit --version
      script:
        - pre-commit install
        - pre-commit run --all-files --verbose
    - <<: *_build_template
      stage: base-images
      name: Base Images
      env:
        - IMAGES_DIR=base-images
    - <<: *_build_template
      stage: child-images
      name: Child Images
      env:
        - IMAGES_DIR=child-images

notifications:
  email:
    on_success: never
    on_failure: always
