dist: bionic

language: python

python:
  - 3.6

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=flaudisio
    - PYTHONUNBUFFERED=1

stages:
  - pre-commit
  - base-images
  - child-images

_build_template: &_build_template
  before_script:
    - docker version
    - docker-compose --version
    - make builder

jobs:
  include:
    - stage: pre-commit
      name: pre-commit
      install:
        - pip install -U pre-commit
      before_script:
        - pre-commit --version
      script:
        - pre-commit install
        - pre-commit run --all-files --verbose
    - <<: *_build_template
      stage: base-images
      name: Base Images
      script:
        - make base-images
    - <<: *_build_template
      stage: child-images
      name: Child Images
      script:
        - make child-images

notifications:
  email:
    on_success: never
    on_failure: always
