dist: bionic

language: python

python:
  - 3.6

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=flaudisio
    - PYTHONUNBUFFERED=1

stages:
  - pre-commit
  - parent-images
  - child-images

_build_template: &_build_template
  install:
    - pip install -r requirements.txt
  before_script:
    - docker version
  script:
    - echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - ./build.py

_parent_image: &_parent_image
  <<: *_build_template
  stage: parent-images

_child_image: &_child_image
  <<: *_build_template
  stage: child-images

jobs:
  include:
    - stage: pre-commit
      name: pre-commit Tests
      install:
        - pip install -U pre-commit
      before_script:
        - pre-commit --version
      script:
        - pre-commit install
        - pre-commit run --all-files --verbose
    - <<: *_parent_image
      name: Ansible
      env:
        - IMAGE=ansible
    - <<: *_parent_image
      name: Cookiecutter
      env:
        - IMAGE=cookiecutter
    - <<: *_parent_image
      name: pre-commit
      env:
        - IMAGE=pre-commit
    - <<: *_child_image
      name: Molecule
      env:
        - IMAGE=molecule
