dist: bionic

language: python

python:
  - 3.6

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=flaudisio
    - PYTHONUNBUFFERED=1

stages:
  - pre-commit
  - base-images
  - child-images

_build_template: &_build_template
  install:
    - pip install -r builder/requirements.txt
  before_script:
    - |
        if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] ; then
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          export ENABLE_PUSH=1
        fi

jobs:
  include:
    - stage: pre-commit
      name: pre-commit
      install:
        - pip install -U pre-commit
        - sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        - sudo chmod -v 755 /usr/local/bin/hadolint
      before_script:
        - pre-commit --version
        - hadolint --version
      script:
        - pre-commit run --all-files --verbose
    - <<: *_build_template
      stage: base-images
      name: Base Images
      script:
        - make base-images
    - <<: *_build_template
      stage: child-images
      name: Child Images
      script:
        - make child-images

notifications:
  email:
    on_success: never
    on_failure: always
