dist: bionic

language: python

python:
  - 3.6

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=flaudisio
    - PYTHONUNBUFFERED=1

stages:
  - pre-commit
  - base-images
  - child-images

_build_template: &_build_template
  install:
    - pip install -r requirements.txt
  before_script:
    - docker version
  script:
    - |
        if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] ; then
          echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
          export ENABLE_PUSH=1
        fi
    - ./build.py

_base_image: &_base_image
  <<: *_build_template
  stage: base-images

_child_image: &_child_image
  <<: *_build_template
  stage: child-images

jobs:
  include:
    - stage: pre-commit
      name: pre-commit Tests
      install:
        - pip install -U pre-commit
      before_script:
        - pre-commit --version
      script:
        - pre-commit install
        - pre-commit run --all-files --verbose
    - <<: *_base_image
      name: Ansible
      env:
        - IMAGE=ansible
    - <<: *_base_image
      name: Cookiecutter
      env:
        - IMAGE=cookiecutter
    - <<: *_base_image
      name: pre-commit
      env:
        - IMAGE=pre-commit
    - <<: *_child_image
      name: Molecule
      env:
        - IMAGE=molecule

notifications:
  email:
    on_success: never
    on_failure: always
