version: '2.2'

services:
  builder:
    build:
      context: builder
    volumes:
      - ./:/docker-images:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME:-dockeruser}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD:-dockerpass}
      ENABLE_PUSH: ${ENABLE_PUSH:-false}
      IMAGES_DIR: /docker-images/${IMAGES_DIR:-base-images}
      IMAGE: ${IMAGE:-all}
