#!/usr/bin/env bash
#
# install-asdf-tools
#
# Helper script to install all ASDF tools defined in a '.tool-versions' file.
#
##

readonly ToolsFile="${ASDF_DEFAULT_TOOL_VERSIONS_FILENAME:=".tool-versions"}"


function _msg()
{
    echo -e "--> $*" >&2
}

function add_plugins()
{
    _msg "Adding plugins"

    grep -v '^#' "$ToolsFile" | cut -d ' ' -f 1 | xargs -I '{}' asdf plugin-add '{}'
}

function install_tools()
{
    # Ignore commented or empty lines
    grep -E -v '^(#.*)*$' "$ToolsFile" \
        | \
        while read -r tool versions ; do
            [[ -z "$tool" ]] && continue

            for version in $versions ; do
                [[ "$version" == "system" ]] && continue

                _msg "Installing $tool $version"

                asdf install "$tool" "$version"
            done
        done
}

function main()
{
    if [[ ! -f "$ToolsFile" ]] ; then
        _msg "Tools file '$ToolsFile' not found; ignoring"
        exit 0
    fi

    add_plugins
    install_tools
}

main "$@"
