---
images:
  - name: pre-commit
    tags:
      - name: 2-alpine
        build_args:
          - pre_commit_version=2.*
        aliases:
          - "2"
          - alpine
          - latest
      - name: 2-debian
        dockerfile: Dockerfile.debian
        build_args:
          - pre_commit_version=2.*
        aliases:
          - debian
