---
# yamllint disable rule:line-length

name: Main

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 */2 * *"

env:
  PYTHONUNBUFFERED: "1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: flaudisio/pre-commit:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Prepare dependencies
        run: |
          install-asdf-tools
          hadolint --version
          pre-commit --version
      - name: Run lint
        run: |
          make lint


  build-images:
    name: Build images
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install builder dependencies
        run: |
          pip install -r builder/requirements.txt
      - name: Build and push images (if enabled)
        env:
          DOCKER_REPOSITORY: docker.io/flaudisio
          DOCKER_USERNAME: flaudisio
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ] ; then
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "$DOCKER_USERNAME" --password-stdin
              export ENABLE_PUSH=1
          fi

          make images/all
