---
# yamllint disable rule:line-length rule:truthy

name: CI/CD

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 */2 * *"

env:
  PYTHONUNBUFFERED: "1"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: flaudisio/pre-commit:latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare dependencies
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
          hadolint --version
          pre-commit --version
      - name: Run tests
        run: |
          make test

  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Build and push images (if enabled)
        env:
          DOCKER_REPOSITORY: docker.io/flaudisio
          DOCKER_USERNAME: flaudisio
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ] ; then
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "$DOCKER_USERNAME" --password-stdin
              export ENABLE_PUSH=1
          fi

          make base-images
          make child-images
