---
# yamllint disable rule:line-length rule:truthy

name: CI/CD

on: [push]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    container:
      image: flaudisio/pre-commit:latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare dependencies
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
          hadolint --version
          pre-commit --version
      - name: Run pre-commit
        run: |
          pre-commit run --all-files --verbose --color always

  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub and enable Docker push
        if: github.ref == 'master'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "$DOCKER_USERNAME" --password-stdin
          export ENABLE_PUSH=1
      - name: Build and push (if enabled)
        run: |
          make base-images
          make child-images
